# Generated by Django 3.2.2 on 2021-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='dghyys', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
